#!/usr/bin/env python3
"""Generate ``docs/AGENT_SKILL_MAP.md`` from the agent package manifests.

Scans every ``agents/*/agent.yaml`` and emits a markdown table mapping each
agent to the skills it declares, split into three columns:

* **Required** - ``required_skills`` (hard prerequisites).
* **Context** - ``context_skills`` (optional / as-relevant skills the agent may
  load depending on the task).
* **Extends** - the base agent inherited via ``extends`` (if any).

This mirrors ``devtools/generate_agent_skill_map.py`` in the core ``neqsim``
repo (which parses ``Loaded skills:`` lines from ``*.agent.md`` files) so the
folder-per-agent catalogs get the same auditable agent<->skill linkage.

The script is intentionally self-contained and identical across the community
and enterprise agent repositories.

Usage:
    python scripts/generate_agent_skill_map.py            # write the map
    python scripts/generate_agent_skill_map.py --check    # fail if stale (CI)

Exit codes:
    0 - map written, or (with --check) the committed map is up to date
    1 - (with --check) the committed map is stale / missing
    2 - a required dependency is missing
"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: PyYAML is required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)


def repo_root_from_script():
    """Return the repository root (parent of this scripts/ folder)."""
    return Path(__file__).resolve().parents[1]


def load_manifest(path):
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None
    return data if isinstance(data, dict) else None


def skill_cell(skills):
    if not skills:
        return "_(none)_"
    return ", ".join("`{}`".format(s) for s in skills)


def build_rows(agents_dir):
    rows = []
    for manifest_path in sorted(agents_dir.glob("*/agent.yaml")):
        manifest = load_manifest(manifest_path)
        name = manifest_path.parent.name
        if manifest is None:
            rows.append({"name": name, "required": [], "context": [], "extends": ""})
            continue
        extends = manifest.get("extends") or {}
        extends_cell = ""
        if isinstance(extends, dict) and extends.get("agent"):
            extends_cell = "`{}` ({})".format(
                extends.get("agent"), extends.get("repo", "?")
            )
        rows.append(
            {
                "name": manifest.get("name", name),
                "required": list(manifest.get("required_skills") or []),
                "context": list(manifest.get("context_skills") or []),
                "extends": extends_cell,
            }
        )
    return rows


def render(rows, repo_label):
    lines = [
        "---",
        "title: Agent to Skill Map",
        "description: Auto-generated map of which skills each {} agent declares, "
        "derived from agents/*/agent.yaml.".format(repo_label),
        "---",
        "",
        "# Agent \u2192 Skill Map",
        "",
        "Auto-generated by `scripts/generate_agent_skill_map.py`. Do not edit by hand.",
        "",
        "`Required` = `required_skills` (hard prerequisites). `Context` = "
        "`context_skills` (optional / as-relevant skills the agent may load "
        "depending on the task). `Extends` = base agent inherited via `extends`.",
        "",
        "| Agent | Required skills | Context skills | Extends |",
        "|-------|-----------------|----------------|---------|",
    ]
    for row in rows:
        lines.append(
            "| `{}` | {} | {} | {} |".format(
                row["name"],
                skill_cell(row["required"]),
                skill_cell(row["context"]),
                row["extends"] or "\u2014",
            )
        )
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=repo_root_from_script(),
        help="Repository root (defaults to the parent of this scripts/ folder).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail if the committed map is missing or stale.",
    )
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    agents_dir = repo_root / "agents"
    if not agents_dir.is_dir():
        print("ERROR: agents/ directory not found at {}".format(agents_dir))
        return 2

    repo_label = "enterprise" if (repo_root / "enterprise-agents.yaml").exists() else "community"
    rows = build_rows(agents_dir)
    document = render(rows, repo_label) + "\n"

    out_path = repo_root / "docs" / "AGENT_SKILL_MAP.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if current.replace("\r\n", "\n") != document.replace("\r\n", "\n"):
            print(
                "ERROR: {} is stale. Run "
                "`python scripts/generate_agent_skill_map.py`.".format(
                    out_path.relative_to(repo_root)
                )
            )
            return 1
        print("Agent-skill map is up to date ({} agents).".format(len(rows)))
        return 0

    out_path.write_text(document, encoding="utf-8")
    print("Wrote {} ({} agents).".format(out_path.relative_to(repo_root), len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
