#!/usr/bin/env python3
"""Generate ``docs/ORCHESTRATION_MAP.md`` from the agent package manifests.

Builds the agent orchestration graph from two manifest fields:

* ``coordinated_agents`` - horizontal delegation edges (a coordinator/front-door
  agent routing to specialist agents).
* ``extends`` - vertical overlay edges (an enterprise agent layering a company
  policy on top of a base community/core agent).

Emits a Markdown table (Agent / Type / Coordinates / Extends) plus a Mermaid
graph of the delegation edges, so the orchestration topology is reviewable and
staleness-gated in CI. Complements ``generate_agent_skill_map.py`` (which maps
agents to skills).

The script is intentionally self-contained and identical across the community
and enterprise agent repositories.

Usage:
    python scripts/generate_orchestration_map.py            # write the map
    python scripts/generate_orchestration_map.py --check    # fail if stale (CI)

Exit codes:
    0 - map written, or (with --check) the committed map is up to date
    1 - (with --check) the committed map is stale / missing
    2 - a required dependency is missing
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("ERROR: PyYAML is required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)


def repo_root_from_script():
    """Return the repository root (parent of this scripts/ folder)."""
    return Path(__file__).resolve().parents[1]


def load_manifest(path):
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None
    return data if isinstance(data, dict) else None


def mermaid_id(name):
    """Return a Mermaid-safe node id for an agent name."""
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def build_rows(agents_dir):
    rows = []
    for manifest_path in sorted(agents_dir.glob("*/agent.yaml")):
        manifest = load_manifest(manifest_path)
        name = manifest_path.parent.name
        if manifest is None:
            rows.append(
                {"name": name, "type": "", "coordinated": [], "extends": ""}
            )
            continue
        extends = manifest.get("extends") or {}
        extends_cell = ""
        if isinstance(extends, dict) and extends.get("agent"):
            extends_cell = "{} ({})".format(extends.get("agent"), extends.get("repo", "?"))
        rows.append(
            {
                "name": manifest.get("name", name),
                "type": manifest.get("agent_type") or "",
                "coordinated": list(manifest.get("coordinated_agents") or []),
                "extends": extends_cell,
            }
        )
    return rows


def render(rows, repo_label):
    lines = [
        "---",
        "title: Agent Orchestration Map",
        "description: Auto-generated map of the {} agent orchestration graph "
        "(delegation via coordinated_agents and overlay via extends), derived "
        "from agents/*/agent.yaml.".format(repo_label),
        "---",
        "",
        "# Agent Orchestration Map",
        "",
        "Auto-generated by `scripts/generate_orchestration_map.py`. Do not edit by hand.",
        "",
        "`Type` = `agent_type`. `Coordinates` = `coordinated_agents` (delegation "
        "edges). `Extends` = base agent via `extends` (policy overlay).",
        "",
        "| Agent | Type | Coordinates | Extends |",
        "|-------|------|-------------|---------|",
    ]
    for row in rows:
        coordinated = (
            ", ".join("`{}`".format(a) for a in row["coordinated"])
            if row["coordinated"]
            else "\u2014"
        )
        lines.append(
            "| `{}` | {} | {} | {} |".format(
                row["name"],
                row["type"] or "\u2014",
                coordinated,
                "`{}`".format(row["extends"]) if row["extends"] else "\u2014",
            )
        )
    lines.append("")

    edges = [(r["name"], t) for r in rows for t in r["coordinated"]]
    lines.append("## Delegation graph")
    lines.append("")
    if edges:
        lines.append("```mermaid")
        lines.append("graph LR")
        for src, dst in edges:
            lines.append(
                "    {}[\"{}\"] --> {}[\"{}\"]".format(
                    mermaid_id(src), src, mermaid_id(dst), dst
                )
            )
        lines.append("```")
    else:
        lines.append(
            "_No `coordinated_agents` delegation edges are declared yet._"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=repo_root_from_script(),
        help="Repository root (defaults to the parent of this scripts/ folder).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail if the committed map is missing or stale.",
    )
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    agents_dir = repo_root / "agents"
    if not agents_dir.is_dir():
        print("ERROR: agents/ directory not found at {}".format(agents_dir))
        return 2

    repo_label = "enterprise" if (repo_root / "enterprise-agents.yaml").exists() else "community"
    rows = build_rows(agents_dir)
    document = render(rows, repo_label) + "\n"

    out_path = repo_root / "docs" / "ORCHESTRATION_MAP.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if current.replace("\r\n", "\n") != document.replace("\r\n", "\n"):
            print(
                "ERROR: {} is stale. Run "
                "`python scripts/generate_orchestration_map.py`.".format(
                    out_path.relative_to(repo_root)
                )
            )
            return 1
        print("Orchestration map is up to date ({} agents).".format(len(rows)))
        return 0

    out_path.write_text(document, encoding="utf-8")
    print("Wrote {} ({} agents).".format(out_path.relative_to(repo_root), len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
